### ISSUE TITLE
About Dataset and Detection Model

### ISSUE THREAD

**Issue by liangying-Ke** [500swapnil/stacked-hourglass#2]
Question 1:
In the example of Keypoint Dataset, there is no Visibility Attribute. I have no idea if I should add the Visibility Attribute to the Dataset when I am training the model.

Question 2:
Is this detection model Single Object Detection?

Question 3:
In other repository like the keypoint detection model on paper with code, their input size of the model are 256X192. Why are your input size of the model is 64x64? Any reference?

**Comment by 500swapnil** [comment]
1. For occluded keypoints or keypoints outside the image, use (-1, -1) as the ground truth. It treats them as a missing keypoint and generates an empty heatmap for it.
2. Yes. It requires images with a single object only. It can be used in a pipeline followed by object detection of the particular object you would like to find keypoints for.
3. Yes. This is a modification of the original stacked hourglass network which has 256x256 size input. The dataset we used it on is in 64x64 images which is why it has the maxpooling layer removed and first convolution layer stride reduced to 1. (This kind of network was used in https://ieeexplore.ieee.org/abstract/document/8205990)

I'm working on adding support for MPII dataset when it can be used for 256x256 images.

**Comment by liangying-Ke** [comment]
Thanks you for the answer.
